name = "learn"
compatibility_date = "2025-09-16"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"

[observability]
enabled = true
head_sampling_rate = 1

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "staging"
